name: Build and Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        env:
          CI: false # Treats warnings as warnings, not errors
      
      - name: Deploy to server via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          # Upload the CONTENTS of the build directory, not the build folder itself
          local_path: './build/*'
          # Ensure remote path points to the /admin directory root (e.g., /var/www/html/admin)
          remote_path: ${{ secrets.SERVER_PATH }}/
          sftp_only: true
          # Replace existing files to avoid stale assets on the server
          delete_remote_files: true
          args: '-o ConnectTimeout=5'
