name: Build and Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
        env:
          CI: false # Treats warnings as warnings, not errors
      
      - name: Deploy to server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          protocol: ftps # Change to 'ftp' if your server doesn't support FTPS
          port: 21 # Default FTP port, change if different
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
